#!/usr/bin/env python3
"""Generate the meeting handout PDF for the Rulebook Drift Monitor."""
import os

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, PageBreak,
    Table, TableStyle, HRFlowable,
)

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Rulebook_Drift_Monitor_Meeting_Handout.pdf")

styles = getSampleStyleSheet()

title = ParagraphStyle("title", parent=styles["Title"], fontSize=22, leading=26, spaceAfter=6, textColor=colors.HexColor("#1a1a2e"))
h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=15, leading=18, textColor=colors.HexColor("#4361ee"), spaceBefore=14, spaceAfter=6)
h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=12, leading=15, textColor=colors.HexColor("#1a1a2e"), spaceBefore=10, spaceAfter=4)
body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14, spaceAfter=6, alignment=TA_LEFT)
bullet = ParagraphStyle("bullet", parent=styles["BodyText"], fontSize=10, leading=13, leftIndent=18)
small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=9, leading=12, textColor=colors.HexColor("#6b7280"))
code = ParagraphStyle("code", parent=styles["Code"], fontSize=9, leading=13, backColor=colors.HexColor("#f5f6fb"), borderPadding=6)

def P(txt, s=body):
    return Paragraph(txt, s)

story = []

story.append(P("Rulebook Drift Monitor", title))
story.append(P("Meeting handout &amp; build plan · CDIR Global 'Agentic Regulator' Hackathon (team dev overview)", small))
story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#4361ee"), spaceAfter=10))

story.append(P("Synthetic-data disclaimer", h2))
story.append(P(
    "<b>All data in this prototype is synthetic and illustrative.</b> The DS rulebook (DS-01..DS-40) is a "
    "paraphrased demonstration schema based on FATF (2020) red-flag indicators and FIC Directive 9 / FIC Act "
    "obligations; rule text is not verbatim from source and must be verified against the source documents before "
    "any production use. The 35 fraud typologies and their transaction fixtures (TYP-001..TYP-035) are fabricated "
    "examples derived from public reporting themes for demonstration only and contain no personal data. "
    "Nothing in this prototype reflects live customer, transaction, or supervisory data."
))
story.append(Spacer(1, 6))

# ---------- 1. What the project is ----------
story.append(P("1 &nbsp;What the project is", h1))
story.append(P(
    "An <b>agentic system</b> for the FIC and FSCA that continuously <b>stress-tests the crypto "
    "AML/KYC rulebook</b> against both documented and self-generated fraud typologies, and hands each "
    "<b>verified detection gap</b> to a named analyst as a <b>drafted candidate red flag</b>. It sits in "
    "the market-monitoring and horizon-scanning stage of the regulatory life cycle and hands into policy "
    "development, with a human approval gate on that boundary."
))
story.append(P(
    "<b>Problem:</b> AI-driven crypto fraud is exploding (TRM: ~500% rise in AI-enabled crypto scams in 2025), but "
    "SA's CASP rulebook relies on static, rule-based detection that predates generative AI (the FATF red-flag "
    "baseline is from 2020). Current flow is reactive and takes months: scam → victims → police → guidance → "
    "manual rule updates. Our system compresses that lag to days."
))

# ---------- 2. What the demo output means ----------
story.append(P("2 &nbsp;What you're seeing in the demo", h1))
story.append(P("The run produces a <b>Ranked Gap Report</b>. Each finding shows:"))
story.append(ListFlowable([
    ListItem(P("<b>Typology</b> — the fraud pattern being stress-tested (e.g. pig-butchering/romance scam, AI-cloned-voice phishing, synthetic identity).", bullet)),
    ListItem(P("<b>MITRE ATLAS</b> — the adversarial-machine-learning framework mapping of that pattern's techniques.", bullet)),
    ListItem(P("<b>Fires rules (green +)</b> — existing indicators that DID trigger; <b>Evades rules (red −)</b> — indicators that should have caught this pattern but DID NOT (the stale/gap rules).", bullet)),
    ListItem(P("<b>Drafted candidate red flag</b> — a single-sentence screening indicator a compliance team should adopt, generated by the LLM (or deterministic template).", bullet)),
    ListItem(P("<b>Evidential basis</b> — where the typology came from (documented source, or novel self-generated).", bullet)),
], bulletType="bullet"))

story.append(P("Two things prove the <b>guardrails</b> work:", body))
story.append(ListFlowable([
    ListItem(P("<b>Critic rejection:</b> a 'Rejected by critic' section shows an implausible/speculative novel generation was <b>discarded</b> (no agent marks its own work).", bullet)),
    ListItem(P("<b>Human approval gate:</b> the report ends waiting for a named analyst to <b>accept / amend / reject</b> each finding — nothing is promoted into guidance automatically.", bullet)),
], bulletType="bullet"))

story.append(P("The run is backed by a full <b>audit trail</b> (auditability &amp; traceability): every step is logged with its node, message, rulebook version and run id.", body))

# ---------- Live output (embedded from a real run, when available) ----------
LIVE_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "live_run.json")
if os.path.exists(LIVE_JSON):
    import json as _json
    with open(LIVE_JSON) as _f:
        live = _json.load(_f)
    story.append(PageBreak())
    story.append(P("6 &nbsp;Live demo output (from an actual run)", h1))
    story.append(P("Run id: <b>{}</b> — exactly what a triggered run produces.".format(live["run_id"]), small))
    shown = live["results"][:8]
    for i, f in enumerate(shown, 1):
        rows = [
            ["#", f'<b>{i}</b>'],
            ["Finding", f"<b>{f['name']}</b> ({f['id']})"],
            ["Fires (rule DID trigger)", f['fires']],
            ["Evades (rule IS stale/gap)", f['evades']],
            ["MITRE ATLAS", f['atlas']],
            ["Evidence", f['basis']],
            ["Drafted candidate red flag", f'&ldquo;{f["flag"]}&rdquo;'],
        ]
        t = Table(rows, colWidths=[1.5*inch, 5.2*inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#eef2ff")),
            ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#d0d7de")),
            ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 8.5),
            ("VALIGN", (0,0), (-1,-1), "TOP"),
            ("LEFTPADDING", (0,0), (-1,-1), 6),
            ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 8))
    if len(live["results"]) > len(shown):
        story.append(P(
            f"<b>…plus {len(live['results']) - len(shown)} further verified findings</b> (total "
            f"<b>{len(live['results'])}</b>), one per evaluated typology/fixture — the same schema as above. "
            f"Full ranked report is in the demo.",
            small,
        ))
    if live.get("discarded"):
        story.append(P("<b>Rejected by critic (guardrail — not promoted):</b>", body))
        for d in live["discarded"]:
            story.append(P(f"• {d['name']} ({d['id']}) — {d['why']}", bullet))
        story.append(Spacer(1, 8))
story.append(P(
    "<b>How to read it:</b> 'Evades rules' are the existing FIC/Directive-9/FATF indicators that "
    "should have caught that fraud pattern but did not — the detection gap. 'Fires rules' are the "
    "ones that did trigger. The drafted candidate red flag is the proposed new screening indicator "
    "a compliance team could adopt. Findings marked GEN-NOVEL are self-generated novel evasion paths "
    "(subject to expert plausibility review); the critic rejects unsupported ones. All rules are "
    "alphanumeric DS-01..DS-40 identifiers from the Drift Sentinel schema.",
    small,
))

# ---------- Forecast / drift analytics overlay ----------
import sys as _sys
import os as _os
_SYS_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
if _SYS_ROOT not in _sys.path:
    _sys.path.insert(0, _SYS_ROOT)
try:
    from agents.loader import load_rulebook, load_typologies
    from agents.forecaster import Forecaster
    fc = Forecaster(load_rulebook(), load_typologies()).forecast()
    trend = fc["trend"]
    story.append(P("7 &nbsp;Prediction layer (forecast analytics)", h1))
    story.append(P(
        "A transparent <b>drift-index overlay</b> is computed in real time from the deterministic library scan "
        "(35 typologies × 40 rules = {} relevant pairs). Today: <b>coverage {:.0%}</b>, "
        "<b>drift index {:.0f}/100</b> ({}, projected to {} in 6 review cycles at current AI-evasion "
        "pressure of {:.0%}). Most at-risk next period: {}.".format(
            fc["coverage"]["pairs"], fc["coverage"]["overall"], fc["drift_index"],
            fc["drift_band"], trend["projection"], fc["ai_pressure"]["share"],
            ", ".join("{} ({} {:.2f})".format(a["typology_id"], a["name"][:22], a["hot_score"])
                      for a in fc["at_risk"][:3]),
        ), body))
    if trend["kind"] == "measured_history":
        bt = " With a roll-one-out backtest: {}".format(
            "MAD {:.2f}, MAPE {:.1f}%, bias {:.3f} (n={})".format(
                trend["backtest"]["mad"], trend["backtest"]["mape"],
                trend["backtest"]["bias"], trend["backtest"]["n_points"])) if trend["backtest"] else ""
        story.append(P(
            "Projection source: <b>measured history</b> — fitted to {} recorded runs/checkpoints of the real "
            "drift-index series (cadence ~{}d) with a widening confidence band.{}\n".format(
                trend["history_count"], trend["cadence_days"], bt),
            body))
    else:
        story.append(P(
            "Projection source: <b>library-scan baseline</b> (<b>{}</b> recorded points so far; 3+ switch to a "
            "measured-history forecast).".format(trend["history_count"]),
            body))
    story.append(P(
        "Methodology: Drift Index = coverage deficit (65 weight) + AI-evasion pressure (20) + severity floor (10) + "
        "AI-novelty concentration (5). With 3+ recorded runs/checkpoints the projection is a damped trend fitted to the "
        "MEASURED drift series (least-squares slope combined with the measured AI-evasion rate) with a confidence band "
        "and hold-out backtest; below that it falls back to a clearly-labelled damped exponential smoothing baseline. "
        "It is a <b>decision-support model</b>, not a "
        "calibrated statistical forecast — every number is reproducible from the library scan and recorded history.",
        small,
    ))
    story.append(Spacer(1, 8))
except Exception as exc:
    story.append(P(f"(Forecast section skipped: {exc})", small))
story.append(PageBreak())

# Sample finding diagram (textual)
story.append(P("Sample finding (abridged):", h2))
sample_table = Table(
    [["Finding", "Stablecoin cross-border payment structuring (TYP-006)"],
     ["Fires", "DS-02, DS-03, DS-19, DS-34, DS-37"],
     ["Evades", "DS-24, DS-38"],
     ["ATLAS", "TA0007 Evasion · T1071 Layer"],
     ["Drafted flag", "\"Structuring stablecoin cross-border payments to exceed thresholds without disclosing originator/beneficiary info may indicate threshold evasion.\""]],
    colWidths=[1.1*inch, 5.6*inch],
)
sample_table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#eef2ff")),
    ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#d0d7de")),
    ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
    ("RIGHTPADDING", (0,0), (-1,-1), 6),
]))
story.append(sample_table)
story.append(Spacer(1, 6))
story.append(P("Note: 'Fires' and 'Evades' can list the same rule when a rule fires on one fixture of the typology but is evaded by another adversarial fixture. The key is which indicators the typology overall defeats.", small))

story.append(PageBreak())

# ---------- 3. Architecture ----------
story.append(P("3 &nbsp;Architecture", h1))
arch_table = Table(
    [["Agent", "Responsibility"],
     ["Orchestrator", "Decomposes the run, routes tasks, runs the two arms in parallel, produces the report."],
     ["Retrieval agent", "Grounds the system: surfaces relevant rules per typology, selects threat intel, drafts candidate red flags."],
     ["Simulation agent", "Two modes: reconciliation (documented typologies) + generation (novel evasion paths)."],
     ["Critic agent", "Independent verifier; re-runs every claim deterministically, discards non-reproducible / implausible findings."],
     ["Rule-evaluation engine", "Deterministic core that steps a synthetic transaction through each rule and records fire/evade — reproducible & auditable."]],
    colWidths=[1.7*inch, 5.0*inch],
)
arch_table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#eef2ff")),
    ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#d0d7de")),
    ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
]))
story.append(arch_table)
story.append(Spacer(1, 10))

# ---------- 4. How to run ----------
story.append(P("4 &nbsp;How to run the project", h1))
story.append(P("Prerequisites: Python 3.9+, and Ollama for the local free LLM (optional).", body))

story.append(P("One-time setup", h2))
story.append(P("brew install ollama<br/>ollama pull llama3.2:1b<br/>pip install langgraph langchain langchain-openai langchain-community flask requests", code))

story.append(P("Run", h2))
story.append(P("cd /Users/kyria/Documents/benji_work/Hackathon/rulebook_drift_monitor", code))
story.append(P("Option A — CLI ranked gap report:", bullet))
story.append(P("python3 -m demo.run<br/>python3 -m demo.run --audit&nbsp;&nbsp;&nbsp;# include audit trail<br/>python3 -m demo.run --json&nbsp;&nbsp;&nbsp;# raw state", code))
story.append(P("Option B — Web demo (open http://127.0.0.1:5000):", bullet))
story.append(P("python3 -m demo.web", code))
story.append(P("If Ollama is off, the system degrades gracefully (deterministic templates) so it never crashes. Make sure <b>ollama serve</b> is running once; if the port is already in use, it's already up.", small))

story.append(PageBreak())

# ---------- 5. 8-day plan ----------
story.append(P("5 &nbsp;8-day build plan (deadline 8 Sep, 23:59 AOE)", h1))
story.append(P("Submission = presentation deck + ≤3-min video demo + testable prototype (NayaOne GitLab). Demo Days 15–16 Sep, Judging 17 Sep. Status as of today (31 Aug): core end-to-end slice DONE.", body))

plan = [
    ["Day 1 · Tue 1 Sep (kick-off)", "Finalise roles; expand rulebook to 30–40 rules; init NayaOne GitLab repo + requirements.txt; shake out demo; rough-cut the video."],
    ["Day 2 · Wed 2 Sep (knowledge clinic)", "Expand typologies to 12–15 with richer fixtures; add real vector store (ChromaDB/FAISS) for RAG; systematise MITRE ATLAS mapper."],
    ["Day 3 · Thu 3 Sep (knowledge clinic)", "Strengthen critic: back-testing re-discovers seeded gaps + plausibility scoring; evaluation harness (recall / false-positive, lead-time); prompt-injection red-team."],
    ["Day 4 · Fri 4 Sep", "Integrate vector store + ATLAS mapper + evaluation into workflow; harden audit trail + human-in-the-loop persistence; interim demo checkpoint."],
    ["Day 5 · Mon 7 Sep (pitch clinic)", "Build 4-min presentation deck (NayaOne template); refine demo/video script; book ≥1 mentor session."],
    ["Day 6 · Tue 8 Sep (pitch clinic + DEADLINE)", "Record 3-min video (end-to-end, guardrails live, downloadable); finalise prototype + README; submit all 3 deliverables to NayaOne before 23:59 AOE."],
    ["Buffer (9–16 Sep)", "Polish visuals; rehearse 4-min pitch to the clock; load-test demo reliability; prep Q&amp;A answers."],
]
rows = [["When", "What to do"]]
rows += plan
t = Table(rows, colWidths=[1.9*inch, 4.8*inch])
t.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#eef2ff")),
    ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#d0d7de")),
    ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
]))
story.append(t)

story.append(Spacer(1, 12))
story.append(P("Task ownership (suggested; combine roles for a smaller team)", h2))
story.append(ListFlowable([
    ListItem(P("<b>Dev A (core):</b> engine, agents, workflow, integration lead.", bullet)),
    ListItem(P("<b>Dev B (data):</b> rulebook + typology expansion, fixtures, vector store.", bullet)),
    ListItem(P("<b>Dev C (eval):</b> MITRE ATLAS mapper, evaluation harness, back-testing.", bullet)),
    ListItem(P("<b>Dev D (product):</b> web app polish, video demo, NayaOne deployment.", bullet)),
    ListItem(P("<b>Pitch/Product:</b> presentation deck, demo narrative, guardrails story.", bullet)),
], bulletType="bullet"))

story.append(P("Guardrails (all mandatory, all demonstrated in the demo):", h2))
story.append(ListFlowable([
    ListItem(P("<b>Human-in-the-loop</b> — analyst accepts/amends/rejects every red flag.", bullet)),
    ListItem(P("<b>Auditability &amp; traceability</b> — full audit trail linking each gap to evidence, rules, ATLAS and analyst.", bullet)),
    ListItem(P("<b>Safety &amp; governance</b> — independent critic discards implausible findings; generation held at indicator level.", bullet)),
    ListItem(P("<b>Cyber risk management</b> — permissioned tool access, confined corpora, public/synthetic data only.", bullet)),
], bulletType="bullet"))

story.append(P("Deliberately NOT built: live blockchain analytics, entity supervision, model fine-tuning. Post-hackathon: extra corpora, FIC STR intake integration, supervised pilot.", body))

doc = SimpleDocTemplate(OUT, pagesize=A4,
                        leftMargin=0.9*inch, rightMargin=0.9*inch,
                        topMargin=0.8*inch, bottomMargin=0.8*inch,
                        title="Rulebook Drift Monitor — Meeting Handout",
                        author="Team")

def footer(canvas, doc_):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.drawString(0.9*inch, 0.45*inch, "Rulebook Drift Monitor · CDIR Agentic Regulator Hackathon")
    canvas.drawRightString(A4[0]-0.9*inch, 0.45*inch, f"Page {doc_.page}")
    canvas.restoreState()

doc.build(story, onFirstPage=footer, onLaterPages=footer)
print("PDF written:", OUT)
